project:
  type: website
  output-dir: docs
  resources:
    - files/

website:
  title: "Matthew Delgado"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Digital Marketing Projects"
        href: digital-marketing.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Résumé"
        href: resume.qmd

format:
  html:
    theme: theme.scss
    toc: true
